"""Step 3b: Re-test existing checkpoints on local split data (no retraining).

This script evaluates each checkpoint in models_dir on the split generated by Step 1.
It supports mixed checkpoint types (6-label and 7-label) and writes final outputs.
"""

from __future__ import annotations

import shutil
from functools import partial
from pathlib import Path
import sys

import pandas as pd
import torch
from torch.utils.data import DataLoader
from transformers import AutoTokenizer

CURRENT = Path(__file__).resolve()
PROJECT_ROOT = CURRENT.parents[1]
PARENT_PIPELINE = CURRENT.parents[2]
sys.path.append(str(PROJECT_ROOT))
sys.path.append(str(PARENT_PIPELINE))

from src.config_loader import load_config, resolve_path
from src.constants import LABELS_6, LABELS_7, LABEL_MAP_6, LABEL_MAP_7
from src.dataset import TikTokEmotionDataset
from src.evaluate import evaluate_with_thresholds, tune_thresholds_constrained
from src.modeling import build_model
from src.text_preprocess import load_slang_dict, normalize_text
from src.train import collect_probs_labels
from src.utils import write_json


def _extract_state_dict(checkpoint_obj):
    if isinstance(checkpoint_obj, dict) and "model_state_dict" in checkpoint_obj:
        return checkpoint_obj["model_state_dict"]
    return checkpoint_obj


def _infer_architecture(state_dict: dict[str, torch.Tensor]) -> str:
    top_modules = {k.split(".")[0] for k in state_dict.keys()}
    if {"multi_vector", "kan_conv", "mva_proj", "cnn_bottleneck"}.issubset(top_modules):
        return "PhoBERT_MVA_KAN_1D"
    if "cnn" in top_modules and "mha" in top_modules:
        return "PhoBERT_DualStream"
    if "mha" in top_modules:
        return "PhoBERT_MHA_MLP"
    if top_modules.issuperset({"phobert", "classifier"}):
        return "PhoBERT_MLP"
    raise ValueError(f"Unknown architecture signature: {sorted(top_modules)}")


def _infer_num_labels(state_dict: dict[str, torch.Tensor], architecture: str) -> int:
    if architecture == "PhoBERT_MVA_KAN_1D":
        return int(state_dict["classifier.layers.1.base_weight"].shape[0])
    return int(state_dict["classifier.3.weight"].shape[0])


def _filter_by_label_set(df: pd.DataFrame, label_names: list[str]) -> tuple[pd.DataFrame, int]:
    label_set = set(label_names)
    before = len(df)
    keep = df["labels"].apply(
        lambda x: isinstance(x, list) and len(x) > 0 and all(lbl in label_set for lbl in x)
    )
    out = df[keep].reset_index(drop=True)
    return out, before - len(out)


def _subset_min_precision(per_label_cfg: dict, label_names: list[str], default_min: float) -> dict[str, float]:
    return {name: float(per_label_cfg.get(name, default_min)) for name in label_names}


def main() -> None:
    cfg = load_config(PROJECT_ROOT / "config" / "project.yaml")

    outputs_dir = resolve_path(PROJECT_ROOT, cfg["paths"]["outputs_dir"])
    outputs_dir.mkdir(parents=True, exist_ok=True)
    models_dir = resolve_path(PROJECT_ROOT, cfg["paths"]["models_dir"])

    val_path = outputs_dir / "val.json"
    test_path = outputs_dir / "test.json"
    if not val_path.exists() or not test_path.exists():
        raise FileNotFoundError("Missing split files. Run scripts/01_prepare_data.py first.")

    val_df_raw = pd.read_json(val_path)
    test_df_raw = pd.read_json(test_path)

    slang_path = resolve_path(PROJECT_ROOT, cfg["paths"]["slang_dict"])
    slang_dict = load_slang_dict(slang_path)
    normalize_fn = partial(normalize_text, slang_dict=slang_dict)

    tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base-v2")
    max_length = int(cfg["dataset"]["max_length"])
    batch_eval = int(cfg["training"]["batch_size_eval"])

    dropout = float(cfg["training"]["dropout"])
    num_heads = int(cfg["training"]["num_heads"])
    grid_size = int(cfg["training"]["grid_size"])

    min_precision_default = float(cfg["threshold_tuning"]["min_precision_default"])
    per_label_cfg = cfg["threshold_tuning"]["per_label_min_precision"]

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    amp_enabled = torch.cuda.is_available()

    model_paths = sorted(models_dir.glob("*.pt"))
    if not model_paths:
        raise FileNotFoundError(f"No model checkpoints found in {models_dir}")

    all_results = []
    ranking_rows = []

    for model_path in model_paths:
        print(f"Evaluating checkpoint: {model_path.name}")

        checkpoint_obj = torch.load(model_path, map_location=device, weights_only=False)
        state_dict = _extract_state_dict(checkpoint_obj)

        architecture = _infer_architecture(state_dict)
        num_labels = _infer_num_labels(state_dict, architecture)

        if num_labels == 6:
            label_names = LABELS_6
            label_map = LABEL_MAP_6
        elif num_labels == 7:
            label_names = LABELS_7
            label_map = LABEL_MAP_7
        else:
            raise ValueError(f"Unsupported number of labels: {num_labels}")

        val_df, val_drop = _filter_by_label_set(val_df_raw, label_names)
        test_df, test_drop = _filter_by_label_set(test_df_raw, label_names)

        if len(val_df) == 0 or len(test_df) == 0:
            raise ValueError(f"No valid samples for {model_path.name} after label filtering.")

        val_ds = TikTokEmotionDataset(val_df, tokenizer, normalize_fn, max_length, label_map)
        test_ds = TikTokEmotionDataset(test_df, tokenizer, normalize_fn, max_length, label_map)

        val_loader = DataLoader(
            val_ds,
            batch_size=batch_eval,
            shuffle=False,
            num_workers=2,
            pin_memory=torch.cuda.is_available(),
        )
        test_loader = DataLoader(
            test_ds,
            batch_size=batch_eval,
            shuffle=False,
            num_workers=2,
            pin_memory=torch.cuda.is_available(),
        )

        model = build_model(
            name=architecture,
            num_labels=num_labels,
            dropout=dropout,
            num_heads=num_heads,
            grid_size=grid_size,
        ).to(device)
        model.load_state_dict(state_dict)
        model.eval()

        val_prob, val_true = collect_probs_labels(model, val_loader, device, num_labels, amp_enabled)
        test_prob, test_true = collect_probs_labels(model, test_loader, device, num_labels, amp_enabled)

        saved_thresholds = None
        if isinstance(checkpoint_obj, dict):
            raw_thr = checkpoint_obj.get("thresholds")
            if raw_thr is not None and len(raw_thr) == num_labels:
                saved_thresholds = raw_thr

        if saved_thresholds is not None:
            thresholds = torch.tensor(saved_thresholds, dtype=torch.float32).cpu().numpy()
            threshold_source = "checkpoint"
            tuning_rows = []
        else:
            per_label_min = _subset_min_precision(per_label_cfg, label_names, min_precision_default)
            thresholds, tuning_df = tune_thresholds_constrained(
                y_true=val_true,
                y_prob=val_prob,
                label_names=label_names,
                min_precision=min_precision_default,
                per_label_min_precision=per_label_min,
            )
            threshold_source = "validation_tuned"
            tuning_rows = tuning_df.to_dict(orient="records")

        test_metrics, report_dict, conf_mtx = evaluate_with_thresholds(
            y_true=test_true,
            y_prob=test_prob,
            thresholds=thresholds,
            label_names=label_names,
        )

        dst_ckpt = outputs_dir / model_path.name
        shutil.copy2(model_path, dst_ckpt)

        record = {
            "model": architecture,
            "model_file": model_path.name,
            "checkpoint": str(dst_ckpt),
            "num_labels": num_labels,
            "labels": label_names,
            "num_samples_val": int(len(val_df)),
            "num_samples_test": int(len(test_df)),
            "dropped_val_rows": int(val_drop),
            "dropped_test_rows": int(test_drop),
            "threshold_source": threshold_source,
            "thresholds": thresholds.tolist(),
            "metrics": test_metrics,
            "classification_report": report_dict,
            "multilabel_confusion_matrix": conf_mtx,
            "threshold_tuning": tuning_rows,
            "source": "split_retest_existing_checkpoints",
        }
        all_results.append(record)

        per_model_file = outputs_dir / f"metrics_{model_path.stem}.json"
        write_json(record, per_model_file)

        ranking_rows.append(
            {
                "model": architecture,
                "model_file": model_path.name,
                "f1_micro": test_metrics["F1-micro"],
                "f1_macro": test_metrics["F1-macro"],
                "f1_weighted": test_metrics["F1-weighted"],
                "accuracy": test_metrics["Accuracy"],
            }
        )

    ranking_df = pd.DataFrame(ranking_rows).sort_values(by="f1_micro", ascending=False)
    ranking_df.to_csv(outputs_dir / "model_ranking.csv", index=False)
    write_json(all_results, outputs_dir / "all_model_results.json")

    print("Completed split re-test for all available checkpoints.")
    print(f"Saved ranking to: {outputs_dir / 'model_ranking.csv'}")


if __name__ == "__main__":
    main()
